<?xml version="1.0" encoding="UTF-8"?>
<!-- Following code is Internal DTD -->
<!DOCTYPE library [
    <!ELEMENT library (book+)>
    <!ELEMENT book (title, author, year, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>
<!-- Use of External CSS for Beautification -->
<?xml-stylesheet type="text/css" href="styles.css"?>
<library>
    <book>
        <title>Web Programming</title>
        <author>Luffy Shaikh</author>
        <year>2025</year>
        <price>400 Rs</price>
    </book>
    <book>
        <title>Web Designing</title>
        <author>Luffy Shaikh</author>
        <year>2024</year>
        <price>300 Rs</price>
    </book>
</library>